language: node_js
node_js:
- 6.11.4
script: 'true'
deploy:
  provider: npm
  email: vladimirdjukic90@gmail.com
  api_key: ${TOKEN}
  skip_cleanup: true
  on:
    tags: false
    repo: vforv/generator-justfast